### ISSUE TITLE
Ensure all lifecycle hooks (options and composition) work

### ISSUE THREAD

**Issue by lmiller1990** [lmiller1990/vue-testing-framework#6]
For some reason, the `onMounted` and other composition API lifecycle hooks are NOT getting triggered. I am not sure why. We should find out.

You can see how Evan tests it here: https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/__tests__/apiLifecycle.spec.ts

**Comment by lmiller1990** [comment]
Ok, it looks like it is stubbing them out - this line is called and returns false

https://github.com/vuejs/vue-next/blob/fe9da2d0e4f9b338252b1b62941ee9ead71f0346/packages/runtime-core/src/apiLifecycle.ts#L73

Seems to think it's SSR when running in Jest?

**Comment by lmiller1990** [comment]
Ok so it is because we are requiring the cjs Vue, which is for SSR - so the lifecycles are stubbed out (cannot mount if there is no DOM)... ref: https://github.com/vuejs/vue-next/blob/master/.github/contributing.md#build-formats

Not sure how we should require Vue 🤔

**Comment by dobromir-hristov** [comment]
Cant we import the `esm` bundle?

**Comment by lmiller1990** [comment]
I will try that - jest was complaining, I think I need to exclude node_modules/Vue in transformPatternIgnore. Which bundle is imported normally when you run tests in Vue cli projects, esm yeah?

**Comment by lmiller1990** [comment]
Got this working! https://github.com/lmiller1990/vue-testing-framework/commit/589c64ced3fa57cc63d0b03aa4069946fd5ec6dc
